mybatis:
  configuration:
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf-8&useSSL=false
    username: dap
    password: dap
  redis:
    host: 10.211.55.130
    port: 6379
  aop:
    proxy-target-class: true

#  rabbitmq:
#    addresses: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

#测试配置对象
report:
  analyse:
    sysConfigList:
      - sysName: 系统名称1
        sysCodeList: a,b,c
      - sysName: 系统名称2
        sysCodeList: d,e,f

es:
  primary: iis
  esConfigMap:
    iis:
      host: 127.0.0.1:9002
      username: iis
      password: 123456
    jwlog:
      host: 127.0.0.2:9002
      username: jwlog
      password: admin123

pdf:
  pdfConfigMap:
    ccl:
      statics:
        use-temp: true
        template:
          dir: pdf/templates/html
          name: ccl_template_freemarker.html
          email-name: ccl_template_email.html
        echarts:
          dir: pdf/templates/echarts
        font:
          dir: D:/jar/temp/pdf/fonts
        image:
          dir: pdf/img
        js:
          dir: pdf/js
          name: phantomjs.js
        tmp:
          dir: ${user.dir}/temp
      server:
        template: http://localhost:${server.port}${server.servlet.context-path:/}pdf/static/ccl_template_freemarker.html
        phantomjs: http://localhost:8002
      ecs:
        sys-code: ICIF
        module-code: CCL
        date-formatter: yyyyMM
        name-pattern: ccl_report_%s.pdf
    cap:
      statics:
        use-temp: true
        template:
          dir: pdf/templates/html
          name: cap_template_freemarker.html
          email-name: cap_template_email.html
        echarts:
          dir: pdf/templates/echarts
        font:
          dir: D:/jar/temp/pdf/fonts
        image:
          dir: pdf/img
        js:
          dir: pdf/js
          name: phantomjs.js
        tmp:
          dir: ${user.dir}/temp
      server:
        template: http://localhost:${server.port}${server.servlet.context-path:/}pdf/static/${template.name}
        phantomjs: http://localhost:8002
      ecs:
        sys-code: ICIF
        module-code: cap
        date-formatter: yyyyMM
        name-pattern: cap_report_%s.pdf

