mybatis:
  configuration:
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf-8&useSSL=false
    username: dap
    password: dap
  redis:
    host: 10.211.55.130
    port: 6379

#  rabbitmq:
#    addresses: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

#测试配置对象
report:
  analyse:
    sysConfigList:
      - sysName: 系统名称1
        sysCodeList: a,b,c
      - sysName: 系统名称2
        sysCodeList: d,e,f

es:
  primary: iis
  esConfigMap:
    iis:
      host: 127.0.0.1:9002
      username: iis
      password: 123456
    jwlog:
      host: 127.0.0.2:9002
      username: jwlog
      password: admin123

