server:
  port: 8010
  servlet:
    session:
      timeout: 0
spring:
  profiles:
    active: dev

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
  level:
    root: info

# 不拦截配置
interceptorconfig:
  path:
    exclude:
      - /user/register
      - /user/login
      - /categories
      - /products
      - /products/*

